lib/media_wiki/gateway.rb: Fix query continuation.
* Query continuation logic has been extracted into private `iterate_query` method.
* XPath selector for query continue parameter updated to match both `@XXfrom` and `@XXcontinue`.
* Query continue parameter for `usercontribs` changed to `uccontinue`, hence pull request #56 obsolete.
* `count` parameter in `contributions` kept for backwards compatibility, though inconsistent with other methods.

Latest release (0.6.0):

* `list('Media')`: "undefined method `value' for nil:NilClass"
* `category_members('Category:Mass media')`: "MediaWiki::APIError: API error: code 'warning', info 'API warning: Unrecognized parameter: 'apfrom''"
* `backlinks('Media')`: 1214
* `users`: 2870
* `contributions('Lucid')`: "undefined method `value' for nil:NilClass"

Before this commit:

* `list('Media')`: 2373 (fixed)
* `category_members('Category:Mass media')`: "MediaWiki::APIError: API error: code 'warning', info 'API warning: Unrecognized parameter: 'apfrom''" (unchanged)
* `backlinks('Media')`: "MediaWiki::APIError: API error: code 'blbadcontinue', info 'Invalid continue param. You should pass the original value returned by the previous query'" (broken by 25493ab)
* `users`: 500 (broken by 030b81f)
* `contributions('Lucid')`: 5076 (fixed)

After this commit:

* `list('Media')`: 2373 (unchanged)
* `category_members('Category:Mass media')`: 100 (fixed)
* `backlinks('Media')`: 1214 (fixed)
* `users`: 2870 (fixed)
* `contributions('Lucid')`: 5076 (unchanged)